# Setup
title:               Metin Gokhan Unal
tagline:             'A Jekyll theme'
description:         'Metin's Personal Website'
url:                 https://mgunal.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Metin Gokhan Unal
  url:               https://twitter.com/mgunal
  email:             mgunal@me.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
